config:
  pdf_path: "statement_pdf.pdf"
  csv_path: "statement.csv"
  source_acc: "Asserts:Bank Accounts:CUB"
  env_file: ".env"

accounts:
  Expenses:
    - name: "Food"
      account: "Expenses:Food"
      description: "Eating out, takeaways, or restaurants"
    - name: "Groceries"
      account: "Expenses:Groceries"
      description: "Monthly grocery and essential household items"
    - name: "Rent"
      account: "Expenses:Rent"
      description: "House or room rent payments"
    - name: "Utilities"
      account: "Expenses:Utilities"
      description: "Electricity, water, and other utilities"
    - name: "Transportation"
      account: "Expenses:Transportation"
      description: "Public transport, auto/taxi, or bus fares"
    - name: "Fuel"
      account: "Expenses:Fuel"
      description: "Petrol, diesel, or EV charging costs"
    - name: "Shopping"
      account: "Expenses:Shopping"
      description: "Clothes, accessories, or general online purchases"
    - name: "Medical"
      account: "Expenses:Medical"
      description: "Healthcare expenses like hospital, medicine, doctor fees"
    - name: "Recharge or Bill Pay"
      account: "Expenses:RechargeOrBillPay"
      description: "Mobile recharges, broadband bills, etc."
    - name: "Subscriptions"
      account: "Expenses:Subscriptions"
      description: "Recurring payments like Netflix, Spotify, etc."
    - name: "Fees or Charges"
      account: "Expenses:FeesOrCharges"
      description: "Bank charges, convenience fees, late fees"
    - name: "Education"
      account: "Expenses:Education"
      description: "Tuition fees, courses, or education-related purchases"
    - name: "Entertainment"
      account: "Expenses:Entertainment"
      description: "Movies, gaming, or fun activities"
    - name: "Travel"
      account: "Expenses:Travel"
      description: "Flight/train bookings, hotels, or tour expenses"
    - name: "Other"
      account: "Expenses:Other"
      description: "Unclassified or miscellaneous expenses"

  Income:
    - name: "Salary"
      account: "Income:Salary"
      description: "Salary or monthly fixed income"
    - name: "UPI Transfer"
      account: "Income:UPITransfer"
      description: "Money received via UPI from others"
    - name: "Refund or Reimbursement"
      account: "Income:RefundOrReimbursement"
      description: "Reimbursements, cashback, or refunds"
    - name: "Interest or Dividend"
      account: "Income:InterestOrDividend"
      description: "Bank interest or investment returns"
    - name: "Gifts"
      account: "Income:Gifts"
      description: "Monetary gifts or presents received"
    - name: "Family"
      account: "Income:Family"
      description: "Money received from family members"
    - name: "Other"
      account: "Income:Other"
      description: "Miscellaneous or uncategorized income"
